[workspace]
members = [ 
    "packages/prism-cli",
    "packages/prism-lib",
    "packages/prism-transpile",
    "packages/prism-wasm"
]
resolver = "2"

[workspace.dependencies.cu]
package = "pistonite-cu"
version = "0.8.4"

[workspace.dependencies]
thiserror = "2.0.18"
num-traits = "0.2.19"
tsify = { version = "0.5.6", default-features = false }
wasm-bindgen = "0.2.126"
csscolorparser = "0.8.3"
resvg = "0.47.0"
tiny-skia = "0.12.0"
usvg = "0.47.0"

swc = "71.0.0"
swc_common = "23.0.2"
swc_ecma_ast = "25.0.0"
swc_ecma_parser = "41.1.2"
swc_ecma_transforms_typescript = "51.0.0"

boa_engine = "0.21.1"
