[workspace]
members = [ 
    "packages/prism-cli",
    "packages/prism-lib",
    "packages/prism-transpile",
    "packages/prism-wasm"
]
resolver = "2"

[workspace.dependencies.cu]
package = "pistonite-cu"
version = "0.7.4"

[workspace.dependencies]
num-traits = "0.2.19"
serde = "1.0.228"
tsify = "0.5.6"
wasm-bindgen = "0.2.114"
