packages:
  - packages/app
  - packages/prism-wasm

catalog:
  "@fluentui/react-components": ^9.74.3
  "@fluentui/react-icons": ^2.0.332
  "@pistonite/pure": ^0.29.7
  "@pistonite/celera": ^0.3.3
  "@pistonite/workex": ^0.2.3
  "@pistonite/webfs": ^0.1.3
  "@pistonite/intwc": ^0.1.6
  "@uidotdev/usehooks": ^2.4.1
  "@types/react": ^19.2.17
  "@types/react-dom": ^19.2.3
  react: ^19.2.7
  react-dom: ^19.2.7
  mono-dev: github:Pistonight/mono-dev#dist
  zustand: ^5.0.3
