packages:
  - packages/app
  - packages/mono-dev
  - packages/intwc
  - packages/intwc/vite-plugin
  - packages/prism-wasm
  - packages/shared-controls

catalog:
  "@fluentui/react-components": ^9.60.0
  "@fluentui/react-icons": ^2.0.274
  "@pistonite/pure": ^0.22.3
  "@pistonite/pure-react": ^0.7.0
  "@pistonite/pure-i18next": ^0.3.1
  "@pistonite/workex": ^0.0.5
  "@types/react": ^18
  "@types/react-dom": ^18
  react: ^18
  react-dom: ^18
  eslint: ^9
  typescript: =5.7.2
  vite: ^6.2.0

