packages:
  - packages/app
  - packages/mono-dev
  - packages/intwc
  - packages/intwc/vite-plugin
  - packages/prism-wasm
  - packages/shared-controls

catalog:
  "@fluentui/react-components": ^9.66.8
  "@fluentui/react-icons": ^2.0.306
  "@pistonite/pure": ^0.26.8
  "@pistonite/pure-react": ^0.7.11
  "@pistonite/pure-i18next": ^0.4.7
  "@pistonite/workex": ^0.1.2
  "@types/react": ^18
  "@types/react-dom": ^18
  react: ^18
  react-dom: ^18
  react-i18next: ^15.6.0
  vite: ^6.3.5

