packages:
  - packages/app
  - packages/mono-dev
  - packages/intwc
  - packages/intwc/vite-plugin
  - packages/prism-wasm
  - packages/shared-controls

catalog:
  "@fluentui/react-components": ^9.61.2
  "@fluentui/react-icons": ^2.0.292
  "@pistonite/pure": ^0.24.1
  "@pistonite/pure-react": ^0.7.3
  "@pistonite/pure-i18next": ^0.3.4
  "@pistonite/workex": ^0.0.7
  "@types/react": ^18
  "@types/react-dom": ^18
  react: ^18
  react-dom: ^18
  vite: ^6.2.2

