version: '3'

includes:
  common:
    taskfile: ./node_modules/mono-dev/task/common.yaml
    flatten: true
    optional: true

  app:
    taskfile: ./packages/app
    dir: ./packages/app
    internal: true

  lib:
    taskfile: ./packages/prism-lib
    dir: ./packages/prism-lib
    internal: true

  wasm:
    taskfile: ./packages/prism-wasm
    dir: ./packages/prism-wasm
    internal: true

  cli:
    taskfile: ./packages/prism-cli
    dir: ./packages/prism-cli
    internal: true
  

tasks:
  install-cargo-extra-tools:
    aliases: [icets]
    cmds:
      - task: cargo-binstall
        vars:
          PACKAGES: wasm-pack
      - task: cargo-binstall
        vars:
          PACKAGES: workex --git https://github.com/Pistonite/workex

  install:
    desc: Install dependencies for local development
    cmds:
      - pnpm install
      - task: post-install

  post-install:
    cmds:
      - task: app:install
      - task: wasm:install

  check:
    desc: Run checks
    cmds:
      - task: lib:check
      - task: wasm:check
      - task: cli:check
      - task: app:check

  test:
    desc: Run tests
    cmds:
      - task: lib:test

  build-dev:
    desc: Sanity build pass
    cmds:
      - task: cli:build
      - task: wasm:wasm-dev-build
      - task: app:build

  build:
    desc: Build for production
    cmds:
      - task: wasm:build
      - task: app:build

  pnpm-dev-link:
    cmds:
      - |
        for f in packages/*/package.json; do
          sed -i 's|"@pistonite/{{.CLI_ARGS}}": "catalog:"|"@pistonite/{{.CLI_ARGS}}": "link:../../../{{.CLI_ARGS}}"|g' "$f"
        done
      - pnpm i

  pnpm-dev-unlink:
    cmds:
      - |
        for f in packages/*/package.json; do
          sed -i 's|"@pistonite/{{.CLI_ARGS}}": "link:../../../{{.CLI_ARGS}}"|"@pistonite/{{.CLI_ARGS}}": "catalog:"|g' "$f"
        done
      - pnpm i

  upgrade:
    - >
      pnpm up -r mono-dev react react-dom @types/react @types/react-dom
      @pistonite/pure @pistonite/celera @pistonite/workex @fluentui/react-components @fluentui/react-icons
      @pistonite/intwc
    - pnpm dedupe
    - pnpm dedupe --check
    - cargo upgrade

  clean:
    - rm -rf node_modules
    - cargo clean
    - rm -rf packages/prism-wasm/target
  
