[package]
name = "prism-cli"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies.prism-lib]
path = "../prism-lib"

[dependencies]
anyhow = "1.0.96"
clap = { version = "4.5.31", features = ["derive"] }
resvg = "0.45.0"
tiny-skia = "0.11.4"
usvg = "0.45.0"

[[bin]]
name = "prism"
path = "src/main.rs"
