[package]
name = "prism-cli"
version = "0.0.0"
edition = "2024"
publish = false

[dependencies.prism-lib]
path = "../prism-lib"

[dependencies.prism-transpile]
path = "../prism-transpile"

[dependencies]
anyhow = "1.0.98"
clap = { version = "4.5.41", features = ["derive"] }
resvg = "0.45.1"
tiny-skia = "0.11.4"
usvg = "0.45.1"

[[bin]]
name = "prism"
path = "src/main.rs"
