[package]
name = "prism-lib"
version = "0.0.0"
edition = "2024"
publish = false

[dependencies]
boa_engine = "0.20.0"
csscolorparser = { version = "0.7.2", features = ["serde"] }
derivative = "2.2.0"
derive_more = { version = "2.0.1", features = ["full"] }
num-traits = "0.2.19"
serde = { version = "1.0.219", features = ["derive"] }
thiserror = "2.0.12"

# WASM stuff
tsify-next = { version = "0.5.6", default-features = false, features = ["js"], optional = true }
wasm-bindgen = { version = "0.2.100", optional = true }

# Additional feature required by WASM
[dependencies.getrandom]
package = "getrandom"
version = "0.2.6"
optional = true

[features]
wasm = [
    "dep:wasm-bindgen", 
    "dep:tsify-next", 
    "dep:getrandom",
    "getrandom/js",
    "boa_engine/js"
]
