version: '3'

includes:
  cargo:
    taskfile: ../mono-dev/task/cargo.yaml
    internal: true

tasks:
  dev:
    desc: Run Tests in Watch Mode
    cmds:
      - cargo watch -x test

  test:
    desc: Run Tests
    cmds:
      - cargo test

  check:
    cmds:
      - task: cargo:clippy-all
      - task: cargo:fmt-check

  fix:
    cmds:
      - task: cargo:fmt-fix
    
