version: '3'

tasks:
  ci:
    cmds:
      - deno install --frozen

  dev:
    desc: Run Vite Dev Server
    cmds:
      - deno run -A npm:vite dev --host

  build:
    desc: Build Client App
    deps: [wasm]
    cmds:
      - deno run -A npm:vite build

  wasm:
    desc: Build WASM Worker Module
    cmds:
      - workex -p app src/wasm/proto.ts
      - wasm-pack build --out-dir src/wasm/lib --target no-modules --release

  check:
    desc: Check for issues
    cmds:
      - deno run -A npm:typescript/tsc --build
      - deno run -A npm:eslint src --report-unused-disable-directives --max-warnings 0 --cache
      - deno run -A npm:prettier . --check

  fix:
    desc: Fix issues
    cmds:
      - deno run -A npm:prettier . --write

