version: '3'

tasks:
  ci:
    cmds:
      - npm ci

  dev:
    desc: Run Vite Dev Server
    cmds:
      - npx vite --host

  build:
    desc: Build Client App
    deps: [wasm]
    cmds:
      - npx vite build

  wasm:
    desc: Build WASM Worker Module
    cmds:
      - task: workex
      - task: wasm-pack
        vars:
          WASM_PACK_ARGS: --release
      - task: wasm-script-lib

  wasm-debug:
    cmds:
      - task: workex
      - task: wasm-pack
        vars:
          WASM_PACK_ARGS: --dev
      - task: wasm-script-lib

  workex:
    cmds:
      - workex -p app src/wasm/proto.ts

  wasm-script-lib:
    cmds:
      - cp ../lib/src/runtime/ts/index.d.ts src/wasm/lib/scriptLib.ts

  wasm-pack:
    cmds:
      - wasm-pack build --out-dir src/wasm/lib --target bundler {{.WASM_PACK_ARGS}}

  check:
    desc: Check for issues
    cmds:
      - npx tsc --build
      - npx eslint src --report-unused-disable-directives --max-warnings 0 --cache
      - npx prettier . --check

  fix:
    desc: Fix issues
    cmds:
      - npx prettier . --write
