version: '3'

includes:
  ecma:
    taskfile: ../mono-dev/task/ecma.yaml
    internal: true

tasks:
  dev:
    cmds:
      - task: ecma:vite-dev

  build:
    cmds:
      - task: ecma:vite-build

  check:
    cmds:
      - task: ecma:mono-check

  fix:
    cmds:
      - task: ecma:mono-fix

  install:
    cmds:
      - cp ../prism-lib/src/runtime/ts/index.d.ts src/PrismLib.ts
