[package]
name = "prism-wasm"
version = "0.0.0"
edition = "2024"
publish = false

[dependencies]
serde = { version = "1.0.218", features = ["derive"] }
tsify-next = { version = "0.5.5", default-features = false, features = ["js"] }
wasm-bindgen = "0.2.100"

[dependencies.prism-lib]
path = "../prism-lib"
features = ["wasm"]

[lib]
crate-type = ["cdylib"]

