version: '3'

includes:
  ecma:
    taskfile: ./node_modules/mono-dev/task/ecma.yaml
    internal: true
    optional: true
  cargo:
    taskfile: ./node_modules/mono-dev/task/cargo.yaml
    internal: true
    optional: true

tasks:
  build:
    cmds:
      - task: cargo:wasm-pack-build
        vars:
          PACKAGE: prism_wasm
          WASM_PACK_ARGS: -t bundler --out-dir src/pkg --no-pack
          TARGET_DIR: ../../target

  wasm-dev-build:
    cmds:
      - task: cargo:wasm-pack-build
        vars:
          PACKAGE: prism_wasm
          WASM_PACK_ARGS: -t bundler --out-dir src/pkg --no-pack --no-opt
          TARGET_DIR: ../../target

  install:
    cmds:
      - workex -p prism --prefix bind src/proto.ts

  check:
    cmds:
      - task: cargo:clippy-all
      - task: cargo:fmt-check
      - task: wasm-dev-build # need to generate the types
      - task: ecma:check

  fix:
    cmds:
      - task: cargo:fmt-fix
      - task: ecma:fix
