name: PR
on:
  pull_request:
    branches:
      - main

jobs:
  check:
    name: check
    runs-on: blacksmith-4vcpu-ubuntu-2204
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
          submodules: true
      - uses: ./.github/steps/setup
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - run: task install-ci
      - run: task check

  test:
    name: test
    runs-on: blacksmith-4vcpu-ubuntu-2204
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
          submodules: true
      - uses: ./.github/steps/setup
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - run: task install-ci
      - run: task test

  build:
    name: build
    runs-on: blacksmith-4vcpu-ubuntu-2204
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
          submodules: true
      - uses: ./.github/steps/setup
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          rust_targets: wasm32-unknown-unknown,x86_64-unknown-linux-gnu
      - run: task install-ci
      - run: task build-dev
