name: PR
on:
  pull_request:
    branches:
      - main

jobs:
  check:
    runs-on: blacksmith-4vcpu-ubuntu-2404
    steps:
      - uses: Pistonight/mono-dev/actions/setup@main
        with:
          runner: blacksmith
          submodules: true
          ecma-pnpm: true
          ecma-bun: true
          rust: stable
          rust-wasm: true
          tool-cargo-binstall: workex=Pistonite/workex
      - run: task install-ci
      - run: task check
  test:
    runs-on: blacksmith-4vcpu-ubuntu-2404
    steps:
      - uses: Pistonight/mono-dev/actions/setup@main
        with:
          runner: blacksmith
          submodules: true
          ecma-pnpm: true
          ecma-bun: true
          rust: stable
          tool-cargo-binstall: workex=Pistonite/workex
      - run: task install-ci
      - run: task test
  build-app:
    runs-on: blacksmith-4vcpu-ubuntu-2404
    steps:
      - uses: Pistonight/mono-dev/actions/setup@main
        with:
          runner: blacksmith
          submodules: true
          ecma-pnpm: true
          ecma-bun: true
          rust: stable
          rust-wasm: true
          tool-cargo-binstall: workex=Pistonite/workex
      - run: task install-ci
      - run: task build-dev
